services:
  app:
    image: ghcr.io/${GITHUB_REPO_OWNER}/techstudyfinder:latest
    container_name: techstudyfinder
    restart: unless-stopped
    ports:
      - "5001:5001"
    env_file:
      - .env
